// Preset lists used by the ComboBox fields in ProjectForm.
// Each value is the literal string written to the project config.
// Users can always pick "Saisir manuellement…" to keep typing free-form,
// and any pre-existing value not present in the list is preserved as a
// custom entry on edit.

export const STORY_GENRE_PRESETS = [
  "Aventure",
  "Action",
  "Mystère / Polar",
  "Thriller",
  "Science-fiction",
  "Fantasy / Heroic fantasy",
  "Fantastique / Surnaturel",
  "Horreur",
  "Comédie",
  "Comédie romantique",
  "Romance",
  "Drame",
  "Drame familial",
  "Tranche de vie",
  "Western",
  "Historique",
  "Biographie / Autobiographie",
  "Documentaire",
  "Reportage / Journalisme BD",
  "Conte / Fable",
  "Super-héros",
  "Espionnage",
  "Cyberpunk",
  "Steampunk",
  "Post-apocalyptique",
  "Dystopie",
  "Uchronie",
  "Jeunesse",
  "Éducatif",
];

export const STORY_TONE_PRESETS = [
  "Léger / Humoristique",
  "Comique / Burlesque",
  "Satirique",
  "Ironique",
  "Tendre",
  "Mélancolique",
  "Nostalgique",
  "Contemplatif",
  "Onirique / Poétique",
  "Sombre",
  "Inquiétant / Angoissant",
  "Tragique",
  "Épique",
  "Héroïque",
  "Sérieux",
  "Solennel",
  "Dramatique",
  "Romantique",
  "Optimiste",
  "Pessimiste",
  "Grinçant / Absurde",
  "Réaliste / Documentaire",
  "Lyrique",
];

export const STORY_SETTING_PRESETS = [
  "Préhistoire",
  "Antiquité — Égypte ancienne",
  "Antiquité — Grèce antique",
  "Antiquité — Rome antique",
  "Moyen Âge",
  "Renaissance",
  "Époque victorienne / 19ᵉ siècle",
  "Belle Époque (1900–1914)",
  "Années folles (1920)",
  "Années 30",
  "Seconde Guerre mondiale",
  "Années 50",
  "Années 60",
  "Années 70",
  "Années 80",
  "Années 90",
  "Années 2000",
  "Époque contemporaine",
  "Futur proche",
  "Futur lointain",
  "Univers post-apocalyptique",
  "Espace / Voyage interstellaire",
  "Monde médiéval-fantastique",
  "Univers steampunk",
  "Univers cyberpunk",
  "Île déserte",
  "Forêt / Nature sauvage",
  "Grande ville moderne",
  "Village rural",
  "Bord de mer / Côte",
  "Montagne / Alpes",
  "Désert",
  "Sous-marin / Océans",
  "Ferme / Campagne",
  "École / Université",
];

export const STORY_AUDIENCE_PRESETS = [
  "Enfants (3–6 ans)",
  "Enfants (7–10 ans)",
  "Pré-ados (10–13 ans)",
  "Adolescents (13–17 ans)",
  "Jeunes adultes (18–25 ans)",
  "Adulte",
  "Tout public / Famille",
  "Ado-adulte",
  "Lecteur·rice averti·e",
  "Public scolaire",
  "Public spécialisé / niche",
];

export const STYLE_ART_STYLE_PRESETS = [
  "Ligne claire",
  "Franco-belge classique",
  "Manga shōnen",
  "Manga shōjo",
  "Manga seinen",
  "Comics américain",
  "Comics indépendant",
  "Roman graphique réaliste",
  "Roman graphique stylisé",
  "Aquarelle douce",
  "Encre lavée / Lavis",
  "Crayon de couleur",
  "Croquis / Carnet de voyage",
  "Peinture numérique",
  "Cartoon / Dessin animé",
  "Caricature",
  "Style minimaliste / Lineart",
  "Pixel art",
  "Album jeunesse illustré",
  "BD européenne contemporaine",
  "Noir et blanc encrage fort",
  "Style graphique géométrique",
  "Réalisme photographique",
  "Semi-réaliste",
  "Style fanzine / underground",
];

export const STYLE_COLOR_PALETTE_PRESETS = [
  "Couleurs vives et saturées",
  "Pastel doux",
  "Tons sépia / Vintage",
  "Noir et blanc",
  "Niveaux de gris",
  "Bichromie (noir + une couleur)",
  "Trichromie limitée",
  "Couleurs chaudes",
  "Couleurs froides",
  "Palette automnale",
  "Palette estivale",
  "Palette hivernale",
  "Palette printanière",
  "Palette désaturée / délavée",
  "Palette néon / fluo",
  "Tons terreux / naturels",
  "Monochrome bleu",
  "Monochrome rouge",
  "Couleurs de l'aube",
  "Couleurs nocturnes / clair-obscur",
  "Aquarelle transparente",
  "Palette rétro années 80",
];

export const STYLE_LINE_WORK_PRESETS = [
  "Trait fin et précis",
  "Trait épais et expressif",
  "Encrage variable / inégal",
  "Trait nerveux / hachuré",
  "Hachures croisées",
  "Sans contour / Aplats purs",
  "Crayonné apparent",
  "Trait à la plume",
  "Trait au feutre",
  "Trait au pinceau",
  "Lineart numérique propre",
  "Trait tremblé / organique",
  "Trait géométrique régulier",
  "Encrage minimaliste",
  "Trait calligraphique",
];

export const STYLE_MOOD_PRESETS = [
  "Lumineuse et joyeuse",
  "Chaleureuse et conviviale",
  "Calme et apaisante",
  "Mélancolique et douce",
  "Onirique et poétique",
  "Mystérieuse",
  "Tendue / Suspense",
  "Angoissante / Oppressante",
  "Dramatique",
  "Épique et grandiose",
  "Énergique / Dynamique",
  "Comique / Légère",
  "Surréelle / Étrange",
  "Nostalgique / Souvenirs d'enfance",
  "Romantique",
  "Hivernale / Glaciale",
  "Estivale / Solaire",
  "Crépusculaire",
  "Nocturne / Clair de lune",
  "Industrielle / Froide",
  "Nature luxuriante",
];

export const STYLE_PANEL_BORDERS_PRESETS = [
  "Cadre noir fin et régulier",
  "Cadre noir épais",
  "Cadre légèrement irrégulier",
  "Cadre tracé à la main, tremblé",
  "Cadre coloré assorti à la scène",
  "Sans cadre / Cases ouvertes",
  "Cadre arrondi",
  "Cadre rectangulaire net",
  "Cadre à double trait",
  "Cadre minimaliste fin gris",
  "Cadre brut au pinceau",
];

export const STYLE_SPEECH_BUBBLES_PRESETS = [
  "Bulles blanches contour fin",
  "Bulles blanches contour épais",
  "Bulles arrondies classiques",
  "Bulles ovales",
  "Bulles rectangulaires (récitatifs)",
  "Bulles à queue pointue dynamique",
  "Bulles tracées à la main, irrégulières",
  "Bulles transparentes",
  "Bulles colorées selon le personnage",
  "Pensées en bulles nuageuses",
  "Cris en bulles déchirées / éclatées",
  "Bulles minimalistes sans contour",
];

export const STYLE_CHARACTER_RENDERING_PRESETS = [
  "Visages ronds, expressions douces",
  "Visages anguleux, traits marqués",
  "Yeux en points",
  "Yeux grands et expressifs (style manga)",
  "Yeux réalistes",
  "Cheveux en aplats simples",
  "Cheveux détaillés",
  "Silhouettes stylisées / cartoon",
  "Proportions réalistes",
  "Proportions caricaturales",
  "Peu d'ombres, aplats",
  "Ombres détaillées / clair-obscur",
  "Hachures pour les ombres",
  "Style chibi / mignon",
  "Anatomie détaillée",
  "Personnages graphiques / minimalistes",
];
